apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generator-chart.fullname" . }}
  labels:
{{ include "generator-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "generator-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "generator-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.args.first }}", "{{ .Values.args.kafkaServers }}", "{{ .Values.args.kafkaTopic }}", "{{ .Values.args.postgresHost }}", "{{ .Values.args.postgresPort }}", "{{ .Values.args.postgresDBname }}", "{{ .Values.args.postgresDbuser }}", "{{ .Values.args.postgresPassword }}"]