# Default values for generator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: http://nexus-new:8081/repository/docker-http/hl7fwa
  tag: 1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

args:
  first: kd
  kafkaServers: localhost:9092
  kafkaTopic: MyPreciousTopic2
  postgresHost: localhost
  postgresPort: 5433
  postgresDBname: claimsdb
  postgresDbuser: admin
  postgresPassword: admin

